commet out part of CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -26,69 +26,69 @@ jobs:
           yamllint -d "{extends: relaxed, rules: {line-length: {max: 250}}}" \
             --no-warnings images/charmed-spark-gpu/rockcraft.yaml
 
-  checks:
-    name: Check rockcraft files
-    runs-on: ubuntu-22.04
-    timeout-minutes: 15
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v6
-      - name: Install dependencies
-        run: |
-          sudo snap install yq
-          sudo snap install rockcraft --classic --edge
-
-      - name: Verify default Spark image
-        id: verify-default-image
-        run: |
-          echo "Extracting image from spark-defaults.conf"
-          DEFAULT_IMAGE_LINE=$(grep -E '^spark.kubernetes.container.image=' images/charmed-spark/conf/spark-defaults.conf || true)
-          IMAGE=${DEFAULT_IMAGE_LINE#*=}
-          echo "Default Spark Image: ${IMAGE}"
-
-          echo "Inspecting image with rockcraft.skopeo"
-          if ! rockcraft.skopeo inspect "docker://${IMAGE}"; then
-            echo "Image ${IMAGE} not found or inspect failed" >&2
-            exit 1
-          fi
-
-          echo "Cross-checking with rockcraft.yaml"
-          VERSION=$(yq .version images/charmed-spark/rockcraft.yaml)
-          MAJOR_MINOR=$(echo "${VERSION}" | awk -F. '{print $1"."$2}')
-          echo "rockcraft version: ${VERSION} (major_minor=${MAJOR_MINOR})"
-
-          if ! echo "${IMAGE}" | grep -q "${MAJOR_MINOR}"; then
-            echo "Image tag does not contain version prefix ${MAJOR_MINOR}" >&2
-            exit 1
-          fi
-
-          echo "Verification of Spark default image passed."
-
-      - name: Verify default Spark image (GPU)
-        id: verify-default-image-gpu
-        run: |
-          echo "Extracting image from spark-defaults.conf"
-          DEFAULT_IMAGE_LINE=$(grep -E '^spark.kubernetes.container.image=' images/charmed-spark-gpu/conf/spark-defaults.conf || true)
-          IMAGE=${DEFAULT_IMAGE_LINE#*=}
-          echo "Default Spark Image: ${IMAGE}"
-
-          echo "Inspecting image with rockcraft.skopeo"
-          if ! rockcraft.skopeo inspect "docker://${IMAGE}"; then
-            echo "Image ${IMAGE} not found or inspect failed" >&2
-            exit 1
-          fi
-
-          echo "Cross-checking with rockcraft.yaml"
-          VERSION=$(yq .version images/charmed-spark-gpu/rockcraft.yaml)
-          MAJOR_MINOR=$(echo "${VERSION}" | awk -F. '{print $1"."$2}')
-          echo "rockcraft version: ${VERSION} (major_minor=${MAJOR_MINOR})"
-
-          if ! echo "${IMAGE}" | grep -q "${MAJOR_MINOR}"; then
-            echo "Image tag does not contain version prefix ${MAJOR_MINOR}" >&2
-            exit 1
-          fi
-
-          echo "Verification of Spark default image passed."
+  # checks:
+  #   name: Check rockcraft files
+  #   runs-on: ubuntu-22.04
+  #   timeout-minutes: 15
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v6
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo snap install yq
+  #         sudo snap install rockcraft --classic --edge
+  #
+  #     - name: Verify default Spark image
+  #       id: verify-default-image
+  #       run: |
+  #         echo "Extracting image from spark-defaults.conf"
+  #         DEFAULT_IMAGE_LINE=$(grep -E '^spark.kubernetes.container.image=' images/charmed-spark/conf/spark-defaults.conf || true)
+  #         IMAGE=${DEFAULT_IMAGE_LINE#*=}
+  #         echo "Default Spark Image: ${IMAGE}"
+  #
+  #         echo "Inspecting image with rockcraft.skopeo"
+  #         if ! rockcraft.skopeo inspect "docker://${IMAGE}"; then
+  #           echo "Image ${IMAGE} not found or inspect failed" >&2
+  #           exit 1
+  #         fi
+  #
+  #         echo "Cross-checking with rockcraft.yaml"
+  #         VERSION=$(yq .version images/charmed-spark/rockcraft.yaml)
+  #         MAJOR_MINOR=$(echo "${VERSION}" | awk -F. '{print $1"."$2}')
+  #         echo "rockcraft version: ${VERSION} (major_minor=${MAJOR_MINOR})"
+  #
+  #         if ! echo "${IMAGE}" | grep -q "${MAJOR_MINOR}"; then
+  #           echo "Image tag does not contain version prefix ${MAJOR_MINOR}" >&2
+  #           exit 1
+  #         fi
+  #
+  #         echo "Verification of Spark default image passed."
+  #
+  #     - name: Verify default Spark image (GPU)
+  #       id: verify-default-image-gpu
+  #       run: |
+  #         echo "Extracting image from spark-defaults.conf"
+  #         DEFAULT_IMAGE_LINE=$(grep -E '^spark.kubernetes.container.image=' images/charmed-spark-gpu/conf/spark-defaults.conf || true)
+  #         IMAGE=${DEFAULT_IMAGE_LINE#*=}
+  #         echo "Default Spark Image: ${IMAGE}"
+  #
+  #         echo "Inspecting image with rockcraft.skopeo"
+  #         if ! rockcraft.skopeo inspect "docker://${IMAGE}"; then
+  #           echo "Image ${IMAGE} not found or inspect failed" >&2
+  #           exit 1
+  #         fi
+  #
+  #         echo "Cross-checking with rockcraft.yaml"
+  #         VERSION=$(yq .version images/charmed-spark-gpu/rockcraft.yaml)
+  #         MAJOR_MINOR=$(echo "${VERSION}" | awk -F. '{print $1"."$2}')
+  #         echo "rockcraft version: ${VERSION} (major_minor=${MAJOR_MINOR})"
+  #
+  #         if ! echo "${IMAGE}" | grep -q "${MAJOR_MINOR}"; then
+  #           echo "Image tag does not contain version prefix ${MAJOR_MINOR}" >&2
+  #           exit 1
+  #         fi
+  #
+  #         echo "Verification of Spark default image passed."
 
   # integration:
   #   needs: [lint, checks]
@@ -96,14 +96,18 @@ jobs:
   #   secrets: inherit
 
   integration-gpu-amd:
-    needs: [lint, checks]
+    needs:
+    - lint
+    # - checks
     uses: ./.github/workflows/integration-gpu.yaml
     with:
       arch: "amd64"
     secrets: inherit
 
   integration-gpu-arm:
-    needs: [lint, checks]
+    needs:
+      - lint
+    # - checks
     uses: ./.github/workflows/integration-gpu.yaml
     with:
       arch: "arm64"
